FROM golang:1.17.2-buster

ENV TZ Asia/Tokyo

COPY install.sh ./
RUN cat install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /artsign

COPY go.mod /artsign/
RUN go mod download

COPY . /artsign/

RUN chmod 755 ./entry-point.sh
ENTRYPOINT [ "./entry-point.sh" ]
