version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    container_name: artsign_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 4306:3306
  storage:
    image: minio/minio:latest
    container_name: artsign_storage
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./tmp/s3/data:/data
    entrypoint: sh
    command: -c 'mkdir -p /data/unit-test /data/local && minio server /data --console-address ":9001"'
    env_file: ./docker.env
  app:
    container_name: artsign_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: "./wait-for-it.sh db:3306 -- air"
    env_file: ./docker.env
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    volumes:
      - bin:/artsign/bin
      - .:/artsign
    ports:
      - 8081:8081
    depends_on:
      - db
volumes:
  bin:
