version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    container_name: artsign_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 4306:3306
