// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTreasurePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type CreateUserLikeCommentInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	CommentID        int     `json:"commentID"`
}

type CreateUserLikeCommentPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type CreateUserLikeInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type CreateUserLikePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type DeleteTreasureInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type DeleteTreasurePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type DeleteUserLikeInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type DeleteUserLikePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
