// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreatePortfolioPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type CreateTreasurePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type CreateUserLikeCommentInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	CommentID        int     `json:"commentID"`
}

type CreateUserLikeCommentPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type CreateUserLikeInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type CreateUserLikePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type DeletePortfolioInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type DeletePortfolioPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type DeleteTreasureInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type DeleteTreasurePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type DeleteUserLikeInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	WorkID           int     `json:"workID"`
}

type DeleteUserLikePayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type DeleteWorkPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type FollowInput struct {
	MyID       int `json:"myID"`
	FolloweeID int `json:"followeeID"`
}

type FollowPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type Message struct {
	ID         int       `json:"id"`
	Content    string    `json:"content"`
	CreatedBy  int       `json:"createdBy"`
	CreateTime time.Time `json:"createTime"`
}

type UnfollowInput struct {
	MyID       int `json:"myID"`
	FolloweeID int `json:"followeeID"`
}

type UnfollowPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
