name: Build and Push ArtSign api to dev cluser

on:
  push:
    branches:
      - yamagai/update-github-actions

jobs:
  build-and-push-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.YAMAGAI_DOCKER_USER }}
          password: ${{ secrets.YAMAGAI_DOCKER_PASSWORD }}

      - name: Docker meta for ArtSign-api
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bamboooo/artsign-api
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build and push ArtSign-api
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: 'artsign-dev'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          access_token_lifetime: 900s
          workload_identity_provider: projects/636847387149/locations/global/workloadIdentityPools/github-actions-2/providers/github-actions-provider
          service_account: 'github-actions@artsign-dev.iam.gserviceaccount.com'

  deploy-to-dev-cluster:
    needs: build-and-push-image
    name: Deploy Art Sign api to dev
    runs-on: ubuntu-latest

    steps:
      - name: Login with gcloud
        run: |-
          gcloud auth login --brief --cred-file="${{ needs.build-and-push-image.auth.outputs.credentials_file_path }}"
          gcloud container clusters get-credentials "artsign-dev-cluster" --zone "asia-east1-a"

      - name: Deploy
        run: |
          kubectl set image -n artsign-api --record deployment/artsign-api artsign-api=${{ needs.build-and-push-image.meta.outputs.tags }}
          kubectl rollout status -n artsign-api deployment/artsign-api
