name: Build and Push ArtSign api to dev cluser

on:
  push:
    branches:
      - yamagai/modify-settings-for-dev

jobs:
  build-and-push-image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set commit hash
        run: echo "::set-output name=COMMIT_HASH::${GITHUB_SHA}"
        id: set-commit-hash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.YAMAGAI_DOCKER_USER }}
          password: ${{ secrets.YAMAGAI_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            bamboooo/artsign-api:${{ steps.set-commit-hash.outputs.COMMIT_HASH }}

  deploy-to-dev-cluster:
    needs: build-and-push-image
    name: Deploy Art Sign api to dev
    runs-on: ubuntu-latest

    steps:
      - name: Kube Set image
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_ARTSIGN_DEV_KUBE_COFIG }}
          version: v1.21.5
          command: set image -n artsign-api --record deployment/artsign-api meshi-api=bamboooo/artsign-api:$GITHUB_SHA

      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_ARTSIGN_DEV_KUBE_COFIG }}
          version: v1.21.5
          command: rollout status -n artsign-api deployment/artsign-api
