// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Portfolio is the predicate function for portfolio builders.
type Portfolio func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)

// Treasure is the predicate function for treasure builders.
type Treasure func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Work is the predicate function for work builders.
type Work func(*sql.Selector)
