// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Work is the predicate function for work builders.
type Work func(*sql.Selector)
